sudo: required
dist: trusty

os: linux
language: cpp
compiler: gcc

addons:
  apt:
    packages: [ man2html, dos2unix, nsis ]

matrix:
  fast_finish: true
  include:
    - compiler: ": Win32"
      env: IMAGEROOT=${HOME}/image-win32 CHOST=i686-w64-mingw32 CBUILD=x86_64-pc-linux-gnu SCRIPT=generic/build
    - compiler: ": Win64"
      env: IMAGEROOT=${HOME}/image-win64 CHOST=x86_64-w64-mingw32 CBUILD=x86_64-pc-linux-gnu SCRIPT=generic/build
    - compiler: ": snapshot"
      env: SCRIPT=windows-nsis/build-snapshot
    - compiler: ": complete"
      env: SCRIPT=windows-nsis/build-complete
    - compiler: ": aarch64"
      env: IMAGEROOT=${HOME}/image CHOST=aarch64-unknown-linux-gnu CBUILD=x86_64-pc-linux-gnu SCRIPT=generic/build

  exclude:
    - compiler: gcc

install:
    - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu xenial main universe"
    - sudo apt-get update
    - sudo apt-get -y install dpkg gcc-mingw-w64 gcc-aarch64-linux-gnu

before_script:
    - unset CC; unset CXX

script:
    - $SCRIPT
