sudo: required
dist: trusty

os: linux
language: cpp
compiler: gcc

addons:
  apt:
    packages: [ man2html, dos2unix, nsis ]

env:
  global:
    - CBUILD=x86_64-pc-linux-gnu

matrix:
  fast_finish: true
  include:
    - compiler: ": Win32"
      env: CHOST=i686-w64-mingw32 SCRIPT=generic/build
    - compiler: ": Win64"
      env: CHOST=x86_64-w64-mingw32 SCRIPT=generic/build
    - compiler: ": Win32 + static"
      env: DO_REALLY_STATIC=1 CHOST=i686-w64-mingw32 SCRIPT=generic/build
    - compiler: ": Win64 + static"
      env: DO_REALLY_STATIC=1 CHOST=x86_64-w64-mingw32 SCRIPT=generic/build
    - compiler: ": Win32 + depcache"
      env: CHOST=i686-w64-mingw32
      script:
        - generic/build --save-depcache=travis
        - generic/build --use-depcache=travis
    - compiler: ": Win64 + depcache"
      env: CHOST=x86_64-w64-mingw32
      script:
        - generic/build --save-depcache=travis
        - generic/build --use-depcache=travis
    - compiler: ": snapshot"
      env: SCRIPT=windows-nsis/build-snapshot
    - compiler: ": complete"
      env: SCRIPT=windows-nsis/build-complete
    - compiler: ": snapshot"
      env: SCRIPT=windows-nsis/build-snapshot OPENSSL_VERSION=1.1.0g
  exclude:
    - compiler: gcc

install:
    - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu xenial main universe"
    - sudo apt-get update
    - sudo apt-get -y install dpkg gcc-mingw-w64

before_script:
    - unset CC; unset CXX

script:
    - $SCRIPT
