sudo: required
dist: trusty

os: linux
language: cpp
compiler: gcc

addons:
  apt:
    packages: [ man2html, dos2unix, nsis ]

env:
  global:
    - CBUILD=x86_64-pc-linux-gnu
    - IMAGEROOT=${HOME}/image

matrix:
  fast_finish: true
  include:
    - compiler: ": Win32"
      env: CHOST=i686-w64-mingw32 SCRIPT=generic/build
    - compiler: ": Win64"
      env: CHOST=x86_64-w64-mingw32 SCRIPT=generic/build
    - compiler: ": Win32 + depcache"
      env: CHOST=i686-w64-mingw32
      script:
        - generic/build --save-depcache=travis
        - generic/build --use-depcache=travis
    - compiler: ": Win64 + depcache"
      env: CHOST=x86_64-w64-mingw32
      script:
        - generic/build --save-depcache=travis
        - generic/build --use-depcache=travis
    - compiler: ": snapshot"
      env: SCRIPT=windows-nsis/build-snapshot
      deploy:
        provider: releases
        api_key:
          secure: PO4ABHgQPoWHGmWxiN9bynDQ3qSAAQ4t+FxAcbs3iTktAewrm8JhWlCKIpI/Gy2Fa59KhY+sSk/Pa8svv80KT/bWpR70fUA6bR/4N+qMb0SjH5X4fOxtHMKbNcAibDytR5utFJ2OKZQZqXZNEaVUtzcuI7ffc2ElB6QYK5dR1GmryB1I6puZyr5X7T7XC61rwfWNL61UheC9VADeWBiTW0/ptYJtwgIi5QIAxYCzs1EJHhvdB3m50pdWWIarCy1WfEjwaRZuL40sFuaGFtjLfIz0ZtlrHsVvsoi3FYwgnGwxXNr00EPjoYHFqgqHgIFjFnDKx815TPzdQR52jawUXJ65Uv+NIEJwQReyWAJyivBJgQhcg4A0vP8SFHmJU74bJHG7ggPOYKD5fhH7zkLHkThWRCJC0zTj5eGw5ppHzi5Qe0DWn1g6qzLRNG/BM2/5QzBx4Gum0x0KKBKA+m3ylcQf1JlyG1nlpUdW4OooRMXs37lQD6a3eEN9EjSc1hJIG5sgsXGXNbiFGKcBlu0nLn2IUYBlH3pmr+6LBn4QvMSa7VqsaxslFDL9Pk9Iqv7ONb8ePYdlJEf52eaqaj5XgyUBdkj6AcRvTxycTa1PSu5W2y9bBYmiFkbbryy2noUkbSHUDE6aXR+7733eGwRZ5MdQi5DYtS19TPmlIke/UgU=
        file: openvpn-install-2.5_git-I601.exe
        on:
          repo: chipitsine/openvpn-build
    - compiler: ": complete"
      env: SCRIPT=windows-nsis/build-complete
  exclude:
    - compiler: gcc

install:
    - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu xenial main universe"
    - sudo apt-get update
    - sudo apt-get -y install dpkg gcc-mingw-w64

before_script:
    - unset CC; unset CXX

script:
    - $SCRIPT
